const qualification = {
    "1":{
        "q_id":1,
        "city_id":1,
        "type":0,
        "title":"您的户籍状况？",
        "brief":"户籍状况",
        "tips":"拥有《北京市工作居住证》或现役武警及驻京部队现役军人的家庭为类京籍。学生集体户口的博士后也视为类京籍。",
        "tips_pc":"拥有《北京市工作居住证》或现役武警及驻京部队现役军人的家庭为类京籍。学生集体户口的博士后也视为类京籍。",
        "is_root":1,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"本地户口/类京籍",
                "next_id":10
            },
            {
                "name":"本地学生集体户口",
                "next_id":22
            },
            {
                "name":"外地户口",
                "next_id":22
            },
            {
                "name":"港澳台地区居民",
                "next_id":23
            },
            {
                "name":"外国人",
                "next_id":24
            }
        ]
    },
    "2":{
        "q_id":2,
        "city_id":1,
        "type":0,
        "title":"您准备在哪里购房？",
        "brief":"购买区域",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"通州",
                "next_id":12
            },
            {
                "name":"北京其他位置",
                "next_id":17
            }
        ]
    },
    "5":{
        "q_id":5,
        "city_id":1,
        "type":0,
        "title":"您准备在哪里购房？",
        "brief":"购买区域",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"通州",
                "next_id":13
            },
            {
                "name":"北京其他位置",
                "next_id":17
            }
        ]
    },
    "10":{
        "q_id":10,
        "city_id":1,
        "type":0,
        "title":"您的婚姻状况？",
        "brief":"婚姻状况",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"已婚",
                "next_id":14,
                "result":"已婚"
            },
            {
                "name":"未婚/离异/丧偶",
                "next_id":15,
                "result":"未婚/离异/丧偶"
            }
        ]
    },
    "12":{
        "q_id":12,
        "city_id":1,
        "type":0,
        "title":"您是否落户通州或近3年在通州连续缴纳社保或个税？",
        "brief":"通州纳税情况",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"是",
                "next_id":17,
                "result":"落户通州或近3年已在通州缴纳社保或个税"
            },
            {
                "name":"否",
                "next_id":18,
                "result":"未落户通州且近3年未在通州缴纳社保和个税"
            }
        ]
    },
    "13":{
        "q_id":13,
        "city_id":1,
        "type":0,
        "title":"您是否近3年在通州连续缴纳社保或个税？",
        "brief":"通州纳税情况",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"是",
                "next_id":17,
                "result":"近3年已在通州缴纳社保或个税"
            },
            {
                "name":"否",
                "next_id":18,
                "result":"近3年未在通州缴纳社保及个税"
            }
        ]
    },
    "14":{
        "q_id":14,
        "city_id":1,
        "type":0,
        "title":"您家庭名下拥有的北京住宅数量是？",
        "brief":"房产数量",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"0套",
                "next_id":16,
                "result":"家庭名下拥有0套北京住宅"
            },
            {
                "name":"1套",
                "next_id":2,
                "result":"家庭名下拥有1套北京住宅"
            },
            {
                "name":"2套及以上",
                "next_id":18,
                "result":"家庭名下拥有2套及以上北京住宅"
            }
        ]
    },
    "15":{
        "q_id":15,
        "city_id":1,
        "type":0,
        "title":"您家庭名下拥有的北京住宅数量是？",
        "brief":"房产数量",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"0套",
                "next_id":17,
                "result":"家庭名下拥有0套北京住宅"
            },
            {
                "name":"1套及以上",
                "next_id":18,
                "result":"家庭名下拥有1套及以上北京住宅"
            }
        ]
    },
    "16":{
        "q_id":16,
        "city_id":1,
        "type":1,
        "title":"2;套",
        "brief":"限购两套",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":""
    },
    "17":{
        "q_id":17,
        "city_id":1,
        "type":1,
        "title":"1;套",
        "brief":"限购一套",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":""
    },
    "18":{
        "q_id":18,
        "city_id":1,
        "type":1,
        "title":"0;套",
        "brief":"不能购买",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":""
    },
    "19":{
        "q_id":19,
        "city_id":1,
        "type":0,
        "title":"您家庭名下拥有的北京住宅数量是？",
        "brief":"房产数量",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"0套",
                "next_id":5,
                "result":"家庭名下拥有0套北京住宅"
            },
            {
                "name":"1套及以上",
                "next_id":18,
                "result":"家庭名下拥有1套以上北京住宅"
            }
        ]
    },
    "22":{
        "q_id":22,
        "city_id":1,
        "type":0,
        "title":"您是否连续60个月（含）以上在本市缴纳社保或个税？",
        "brief":"连续60个月（含）以上在本市缴纳社保和个税",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"是",
                "next_id":19,
                "result":"连续60个月已在北京缴纳社保或个税"
            },
            {
                "name":"否",
                "next_id":18,
                "result":"未能连续60个月在北京缴纳社保及个税"
            }
        ]
    },
    "23":{
        "q_id":23,
        "city_id":1,
        "type":0,
        "title":"您是否国内无房产且在北京有一年居住证明",
        "brief":"国内无房产且在北京有一年居住证明",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"是",
                "next_id":17,
                "result":"国内无房产且在北京有一年居住证明"
            },
            {
                "name":"否",
                "next_id":18,
                "result":"国内有房产或在北京无一年居住证明"
            }
        ]
    },
    "24":{
        "q_id":24,
        "city_id":1,
        "type":0,
        "title":"您是否已经办理了《临时住宿登记表》及《涉外审批单》?",
        "brief":"已经办理了《临时住宿登记表》及《涉外审批单》",
        "tips":"",
        "is_root":0,
        "ctime":"",
        "mtime":"",
        "option":[
            {
                "name":"是",
                "next_id":17,
                "result":"办理了《临时住宿登记表》及《涉外审批单》"
            },
            {
                "name":"否",
                "next_id":18,
                "result":"未办理《临时住宿登记表》或《涉外审批单》"
            }
        ]
    }
};
export default qualification;